import { Recipe } from '../../models/Recipe';

export const MOCK_RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'Fried Rice',
    time: 15,
    matchScore: 8,
    totalItems: 10,
    image: 'https://images.unsplash.com/photo-1685521201966-f0d474dfb133?w=400&h=300&fit=crop',
    ingredients: [
      'Cooked Rice',
      'Eggs',
      'Soy Sauce',
      'Garlic',
      'Ginger',
      'Vegetables (Carrots, Peas, Onion)',
      'Green Onions',
      'Sesame Oil',
    ],
    instructions: [
      'Heat oil in a large pan over high heat.',
      'Add minced garlic and ginger, stir-fry for 30 seconds.',
      'Add chopped vegetables, stir continuously for 2-3 minutes.',
      'Push vegetables to the side, scramble eggs in empty space.',
      'Add cooked rice, break any clumps with spatula.',
      'Pour soy sauce and sesame oil, toss to combine.',
      'Add green onions and serve hot.',
    ],
    description: 'A quick and delicious stir-fried rice with eggs and vegetables.',
    difficulty: 'Easy',
    servings: 2,
  },
  {
    id: '2',
    title: 'Tomato Soup',
    time: 25,
    matchScore: 7,
    totalItems: 9,
    image: 'https://images.unsplash.com/photo-1547592166-7aae4d755744?w=400&h=300&fit=crop',
    ingredients: [
      'Canned Tomatoes',
      'Onion',
      'Garlic',
      'Vegetable Broth',
      'Cream',
      'Basil',
      'Olive Oil',
      'Salt & Pepper',
    ],
    instructions: [
      'Dice onion and crush garlic.',
      'Heat olive oil, sauté onion until translucent.',
      'Add garlic, cook for 1 minute.',
      'Pour in canned tomatoes and vegetable broth.',
      'Simmer for 15 minutes.',
      'Blend until smooth using an immersion blender.',
      'Stir in cream, add basil, salt, and pepper to taste.',
      'Serve hot with crusty bread.',
    ],
    description: 'A smooth and creamy tomato soup perfect for any season.',
    difficulty: 'Easy',
    servings: 4,
  },
  {
    id: '3',
    title: 'Green Goddess Salad',
    time: 10,
    matchScore: 9,
    totalItems: 11,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop',
    ingredients: [
      'Mixed Greens',
      'Arugula',
      'Avocado',
      'Cucumber',
      'Green Apple',
      'Basil',
      'Parsley',
      'Lemon Juice',
      'Olive Oil',
      'Pumpkin Seeds',
      'Feta Cheese',
    ],
    instructions: [
      'Wash and dry mixed greens and arugula thoroughly.',
      'Slice cucumber and green apple into thin pieces.',
      'Cut avocado in half, remove pit, and slice.',
      'Combine greens, arugula, cucumber, apple, and avocado in a large bowl.',
      'Make dressing: whisk lemon juice, olive oil, minced basil, and parsley.',
      'Pour dressing over salad and toss gently.',
      'Top with pumpkin seeds and crumbled feta cheese.',
      'Serve immediately.',
    ],
    description: 'A fresh and vibrant salad loaded with green goodness.',
    difficulty: 'Easy',
    servings: 2,
  },
];
